---
# Headless service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xyme-cache
  name: xyme-cache
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: xyme-cache
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: prometheus
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: xyme-cache
  type: ClusterIP
  clusterIP: None
