apiVersion: apps/v1
kind: Deployment
metadata:
  name: xyme-cache
  namespace: {{ .Release.Namespace }}
  labels:
    app: xyme-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xyme-cache
  template:
    metadata:
      labels:
        app: xyme-cache
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
        kube/nodetype: {{ .Values.nodeSelector }}
      tolerations:
        - operator: Equal
          key: dedicated
          value: {{ .Values.nodeSelector }}
          effect: NoSchedule
      {{- end }}
      serviceAccountName: xyme-service
      containers:
        - image: "{{ required "Provide a value for ecrUrl." .Values.ecrUrl }}/{{ required "Provide a value for imageRepo. Most likely 'xyme-backend'" .Values.imageRepo }}:cache-{{ required "Provide a value for imageTag. Most likely 'vX.X.X'" .Values.imageTag }}"
          imagePullPolicy: IfNotPresent
          name: xyme-cache
          command:
            - python3
            - '-m'
            - app
            - cache
            - '--deploy'
            - '-a'
            - 0.0.0.0
          envFrom:
            - configMapRef:
                name: xyme-config
          ports:
            - name: xyme-cache
              containerPort: 8080
              protocol: TCP
            - name: prometheus
              containerPort: 9090
              protocol: TCP
          volumeMounts:
            - name: nfs
              mountPath: "/mnt/"
              subPath: "system/{{ .Release.Namespace }}/accern/{{ .Values.efsMount | default "xyme" }}"
            - name: cache
              mountPath: /cache
            - name: xyme-backend
              mountPath: /xyme/xyme-backend
            - name: xyme-license
              mountPath: /xyme/xyme-license
          resources:
            limits:
              memory: "4Gi"
            requests:
              memory: "2Gi"
      volumes:
        - name: xyme-backend
          configMap:
            name: xyme-backend
        - name: xyme-license
          configMap:
            name: xyme-license
        - name: nfs
          persistentVolumeClaim:
            claimName: {{ required "Provide a value for efsClaim." .Values.efsClaim }}
        - name: cache
          emptyDir:
            medium: Memory
