apiVersion: v1
kind: ConfigMap
metadata:
  name: xyme-scripts
data:
  {{- $files := .Files }}
  {{ range .Values.scripts  }}
  {{- $script :=  list "scripts/" .name ".py" | join ""}}
  {{ .name }}.py: |
{{ $files.Get $script | indent 4}}

  {{ if .config }}
  {{ .name }}.json: |
{{ .config | toPrettyJson | indent 4 }}
  {{ end }}
  {{ end }}
