kind: Service
apiVersion: v1
metadata:
  name: accern-platform-api
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: accern-platform-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4000
  type: ClusterIP
