kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: xyme-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - pods
      - replicationcontrollers
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - deployments/scale
      - deployments/status
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - update
      - patch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - list
      - get
      - delete
      - deletecollection
      - patch
      - update
  - apiGroups:
      - extensions
    resources:
      - deployments
      - deployments/scale
      - deployments/status
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - update
      - patch

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: xyme-service
  namespace: {{ .Release.Namespace }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: xyme-service-xyme-role-biding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: xyme-service
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: xyme-role
  apiGroup: rbac.authorization.k8s.io
