kind: ServiceAccount
apiVersion: v1
metadata:
  name: accern-api
  namespace: {{ .Release.Namespace  }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: accern-platform-api-role
  namespace: {{ .Release.Namespace }}
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
      - sparkoperator.k8s.io
    resources:
      - pods
      - sparkapplications
      - scheduledsparkapplications
  - apiGroups:
      - hyperion.accern.com
    resources:
      - luceneindices/status
      - refreshrequests/status
      - streamingpipelines/status
      - historicalpipelines/status
      - scheduledpipelines/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - hyperion.accern.com
    resources:
      - luceneindices
      - refreshrequests
      - streamingpipelines
      - historicalpipelines
      - scheduledpipelines
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: accern-platform-api-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: accern-platform-api-role
subjects:
  - kind: ServiceAccount
    name: accern-api
    namespace: {{ .Release.Namespace }}
---